### PR TITLE
Add `router.memory()`

### PR DESCRIPTION
**Pull request by artemave**
For testing without changing url in the browser address bar.

### CODE REVIEW

**Comment by joshski** [comment]
I like this, not so sure about naming...
This is a new “history” isn’t it? But it looks like it’s a new “router” when you build it (`router.memory()`).
A “history” isn’t really a noun though. I guess you don’t want another import, so it’s convenient to define it as a member of `hyperdom.router`?
Maybe `router.history.memory()` or `router.history('memory')` would be clearer though?

**Comment by artemave** [comment]
There are currently two history implementations: `router.pushState` and `router.hash`. This pr simply follows the convention and adds a third one. I agree with your point, but changing the convention seems out of scope.

**Comment by joshski** [comment]
Yep fair point

**Comment by refractalize** [comment]
merge when ready @artemave

**Pull request merged**
